#!/usr/bin/env python3

import pathlib
import re
import sys


def symbol_name(path: pathlib.Path) -> str:
    return "kFont_" + re.sub(r"[^A-Za-z0-9_]", "_", path.name)


def write_byte_array(out, name: str, data: bytes) -> None:
    out.write(f"alignas(4) static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        values = ", ".join(f"0x{byte:02x}" for byte in chunk)
        out.write(f"\t{values},\n")
    out.write("};\n\n")


def main() -> int:
    if len(sys.argv) < 3:
        print("usage: embed_vgui_fonts.py <output.cpp> <font> [<font> ...]", file=sys.stderr)
        return 2

    output = pathlib.Path(sys.argv[1])
    fonts = [pathlib.Path(arg) for arg in sys.argv[2:]]
    output.parent.mkdir(parents=True, exist_ok=True)

    with output.open("w", encoding="ascii", newline="\n") as out:
        out.write("// Generated by scripts/embed_vgui_fonts.py. Do not edit by hand.\n")
        out.write('#include "EmbeddedVGUIFonts.h"\n\n')
        out.write("namespace\n{\n")

        entries = []
        for font in fonts:
            name = symbol_name(font)
            write_byte_array(out, name, font.read_bytes())
            entries.append((font.name, name))

        out.write("static const EmbeddedVGUIFontFile kEmbeddedFonts[] = {\n")
        for filename, name in entries:
            out.write(f'\t{{ "{filename}", {name}, sizeof( {name} ) }},\n')
        out.write("};\n")
        out.write("}\n\n")

        out.write("const EmbeddedVGUIFontFile *VGUI2_GetEmbeddedFontFiles( size_t *count )\n")
        out.write("{\n")
        out.write("\tif ( count )\n")
        out.write("\t\t*count = sizeof( kEmbeddedFonts ) / sizeof( kEmbeddedFonts[0] );\n")
        out.write("\treturn kEmbeddedFonts;\n")
        out.write("}\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
